spring.cloud.gateway.routes:
  - id: beer-service
    predicates:
      - Path=/api/v1/beer,/api/v1/beer/*,/api/v1/beerupc/*
    uri: lb://beer-service

  - id: beerorder-service
    predicates:
      - Path=/api/v1/customers/**
    uri: lb://beerorder-service

  - id: inventory-service
    predicates:
      - Path=/api/v1/beer/*/inventory
    uri: lb://inventory-service