spring.cloud.gateway.routes:
  - id: beerservice
    predicates:
      - Path=/api/v1/beer,/api/v1/beer/*,/api/v1/beerupc/*
    uri: http://localhost:8080

  - id: orderservice
    predicates:
      - Path=/api/v1/customers/**
    uri: http://localhost:8082

  - id: inventory
    predicates:
      - Path=/api/v1/beer/*/inventory
    uri: http://localhost:8081

